fit:
  model:
    class_path: gpcrscan.models.model_module.PDBModelModuleGPCR
    init_args:
      batch_size: 64
      l1_strength: 0.0
      l2_strength: 0.0
      model: 
        # class_path: gpcrscan.models.model.BestGPCR
        # class_path: gpcrscan.models.model.BestGPCRv231 #BestMultiTaskGpcr
        class_path: gpcrscan.models.mamba_models.BestGPCR

        init_args:
          test: "--Lets Start--"
      optimizer_name: AdamW  #Adam #RMSprop #Adadelta #AdamW #Adagrad
      learning_rate: 0.0003
      weight_decay: 0.0001
      scheduler_name: ReduceLROnPlateau
      scheduler_monitor: loss_epoch

  data:
    class_path: gpcrscan.core.folddataloader.PDBFoldDataModule
    init_args:
      batch_size: 512
      num_workers: 10
      protein_tokenizer_filename: "./configs/GPCR_prot_tokenizer.json"
      ligand_tokenizer_filename: "./configs/Chembl_v33_tokenizer.json"

      canonical_smiles_col_name: canonical_smiles
      msa_col_name : protein_seq #noMSA_protein_seq #exclude_terminal #protein_seq # exclude_terminal #"protein_seq" #"exclude_terminal" # #"Align_Sequence"  
      y_col_name : plog_endpoint # endpoint # #endpoint #plog_endpoint #"endpoint"   # "pEndPoint"  #plog_endpoint


    data: /home/lab09/DEV/GPCRScan/data/v4//deepgpcr_non_train_prof_v4.parquet
    val: /home/lab09/DEV/GPCRScan/data/v4//deepgpcr_non_val_prof_v4.parquet
    test: /home/lab09/DEV/GPCRScan/data/v4//deepgpcr_non_test_prof_v4.parquet
    test2_files: "/home/lab09/DEV/GPCRScan/data/v4//deepgpcr_antagonist_test_prof_v4.parquet, /home/lab09/DEV/GPCRScan/data/v4//v6_less_interaction_proteins_v4.parquet, /home/lab09/DEV/GPCRScan/data/v4//deepgpcr_agonist_test_prof_v4.parquet, /home/lab09/DEV/GPCRScan/data/v4//first_frac_alzhemeirs_v4.parquet, /home/lab09/DEV/GPCRScan/data/v4//deepgpcr_non_test2_prof_v4.parquet"



      cv: false
      dataset_name: GPCR_combined
      # dataloader:
      #   class_path: gpcrscan.core.pdbdataset.GPCRDataset
      #   init_args:
      #     protein_tokenizer_filename: "/home/lab09/DEV/GPCRScan/configs/GPCR_prot_tokenizer.json"
      #     ligand_tokenizer_filename: "/home/lab09/DEV/GPCRScan/configs/GPCR_ligand_tokenizer.json"
  trainer:
    max_epochs: 3
    limit_train_batches: .01
    limit_val_batches: .05
    # deterministic: True
    precision: 16-mixed
    accelerator: gpu
    fast_dev_run: false
    default_root_dir: "/scratch/lab09/GPCRScan/dumps/checkpoints"
    enable_model_summary: true
    check_val_every_n_epoch: 1
    num_sanity_val_steps: null
    log_every_n_steps: 100
    enable_checkpointing: true
    enable_model_summary: true
    # accumulate_grad_batches: 1
    num_sanity_val_steps: 0

    logger: true
    # checkpoint_callback: true
        
    default_root_dir: null


    callbacks:
      class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        min_delta: 0.0
        patience: 5
        verbose: false
        mode: min
        strict: true
        check_finite: true
        check_on_train_epoch_end: true
      class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        mode: min
        save_top_k: 1
        save_last: true
        filename: "{epoch}-{val_loss:.2f}"
        dirpath: "/scratch/lab09/GPCRScan/dumps/checkpoints"
        verbose: true
        save_weights_only: false
        auto_insert_metric_name: true
      class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "epoch"
      class_path: lightning.pytorch.callbacks.ModelSummary
      init_args:
        max_depth: 2
    logger:
      class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        # name: "GPCRScan-disolay"
        project: "GPCRScan"
        save_dir: "/scratch/lab09/GPCRScan/dumps/wandb"
        log_model: all
        log_code: true
        log_config: true
        tags: ["RMSprop"]
        notes: "GPCRScan Azoth Data EC50 "
        sync_tensorboard: true
      class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: "/scratch/lab09/GPCRScan/dumps/tensorboards"
        name: "logs"
        # version: "0.0.1"
        # default_hp_metric: False
  # ckpt_path: "./tensorboards/logs/version_30/checkpoints/epoch=429-step=506540.ckpt"
  seed_everything: 89