fit:
  data:
    class_path: gpcrscan.core.folddataloader.PDBFoldDataModule
    init_args:
      batch_size: 1024
      canonical_smiles_col_name: canonical_smiles
      cv: true
      data: /scratch/lab09/GPCRScan/data/train_fold_9.parquet
      dataset_name: GPCR_combined
      dm_filename: ./data/AzothBio/processed/dm.h5
      ligand_tokenizer_filename: ./configs/Chembl_v33_tokenizer.json
      msa_col_name: protein_seq
      num_workers: 16
      protein_tokenizer_filename: ./configs/GPCR_prot_tokenizer.json
      split_size: 0.98
      test: /scratch/lab09/GPCRScan/data/test_fold_9.parquet
      test2_files: /scratch/lab09/GPCRScan/data/v5_antagonist_test.parquet, /scratch/lab09/GPCRScan/data/v5_agonist_test.parquet,
        /scratch/lab09/GPCRScan/data/v6_less_interaction_proteins.parquet, /scratch/lab09/GPCRScan/data/v6_less_interaction_proteins.parquet,  /scratch/lab09/GPCRScan/data/first_frac_alzhemeirs.parquet
      val: /scratch/lab09/GPCRScan/data/v5_combined_test.parquet
      y_col_name: plog_endpoint
  model:
    class_path: gpcrscan.models.model_module.PDBModelModuleGPCR
    init_args:
      batch_size: 64
      l1_strength: 0.0
      l2_strength: 0.0
      learning_rate: 0.0003
      model:
        class_path: gpcrscan.models.mamba_models.BestGPCR
        init_args:
          test: --Lets Start--
      optimizer_name: Adam
      scheduler_monitor: val_loss
      scheduler_name: ReduceLROnPlateau
      weight_decay: 0.0001
  seed_everything: 143
  trainer:
    accelerator: gpu
    callbacks:
      class_path: lightning.pytorch.callbacks.ModelSummary
      init_args:
        max_depth: 2
    check_val_every_n_epoch: 10
    default_root_dir: /scratch/lab09/GPCRScan/dumps/checkpoints
    enable_checkpointing: true
    enable_model_summary: true
    fast_dev_run: false
    log_every_n_steps: 100
    logger:
      class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        name: logs
        save_dir: /scratch/lab09/GPCRScan/dumps/tensorboards
    max_epochs: 3000
    num_sanity_val_steps: 0
    precision: 16-mixed
